# Generated by Django 5.0 on 2024-05-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
