# Generated by Django 5.0 on 2024-05-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
